### ISSUE TITLE
Show buildstep status in the Console View

### ISSUE THREAD

**Issue by erikbsap** [SAP/InfraBox#110]
## Problem

When one clicks from the graph of builds into a single one that failed and wants to find out what actually went wrong, one has to look through multiple steps and guess depending on the limited output whether this was the step that failed or not.

## Solution

Put a 👍  or 👎 on the right side of each step depending on whether this step's return code was 0 or something else.

**Comment by ib-steffen** [comment]
We are not executing the steps, we only start the docker container. So the only return code we get is the one of the entire container. So we cannot look at individual steps and mark them easily.

**Comment by erikbsap** [comment]
Hm. That makes it harder, true. But you also print the steps and their outputs on the fly, right? So there must be some kind of communication happening between what's running inside the container and the UI.

**Comment by ib-steffen** [comment]
there's no real communication. We only parse the output and based on "Step " or "##" we create a section in the ui. So what we could do is to scane the output for "error", but this may have many false positives.

**Comment by erikbsap** [comment]
Wait, you're serious? I thought you were joking. This is a very standard element of a CI-tool UI. If the most obvious way doesn't work, then find not-so-obvious one. That's called software development. "We are not tracking that until now" is not a good response to "Please track that".
