### ISSUE TITLE
Pushing Git tag does not trigger InfraBox build

### ISSUE THREAD

**Issue by musse** [SAP/InfraBox#122]
**Describe the bug**
Pushing a tag to a GitHub repo configured with InfraBox does not trigger any build.

**To Reproduce**
1. Create Git tag and push it to a GitHub repo configured with InfraBox
2. To confirm:
  - Check on the GitHub repo config that the tag creation payload has been delivered to InfraBox
  - Check on the InfraBox UI that no build has been triggered

**Expected behavior**
Pushing a tag to a GitHub repo should trigger an InfraBox build on which the default `tag` value is the name of the tag instead of `build_<number>`.

**Comment by ib-steffen** [comment]
This was caused by manually removing the `Push` event from the webhook.
