### ISSUE TITLE
Slack channel only available to *@infrabox.net

### ISSUE THREAD

**Issue by jannemagnusson** [SAP/InfraBox#125]
**Describe the bug**
The README suggests to jump on your slack channel to get in touch. However, this is only open to people with an @infrabox.net email address.

**To Reproduce**
1. Go to "https://github.com/SAP/InfraBox"
2. Scroll down to "How to obtain support"
3. Click the link "infrabox.slack.com"
4. Look below the login box
5. There you will find "If you have an @infrabox.net email address, you can create an account."

**Expected behavior**
I expected to be able to create an account with any valid email address (for example <name>.<lastname>@ericsson.com), alternatively, that the slack link was an invite link like for the argo project (https://join.slack.com/t/argoproj/shared_invite/<invite key>)

**Additional context**
I work as a CI Architect at Ericsson and we are investigation tools to build a future CI platform on. Infrabox is one of the alternatives, but we want to be able to be part of a community and discuss plans, roadmaps etc. This is quite hard without proper communication channels, like slack. Github issues seems quite inadequate for this purpouse.

**Comment by ib-steffen** [comment]
sorry our fault. please use https://join.slack.com/t/infrabox/shared_invite/enQtNDM5OTUzNzg4NjU3LWFiNWY1MDYyZTA3MmUxNWNmZjgwNWEzZTI0NGYzN2U5OTFjYjQyNTBmNWE0NTYzOGJlOTdmZWI3NmQ3OTQ0MDA 
to join

**Comment by jannemagnusson** [comment]
Thank you!
