### ISSUE TITLE
mark jobs with failed tests as UNSTABLE

### ISSUE THREAD

**Issue by epDHowwD** [SAP/InfraBox#139]
**Is your feature request related to a problem? Please describe.**
When having test failures, InfraBox ignores this and only listens on the container return code. If the container does not artificially check if there are failed tests, InfraBox will mark the job successful. 

**Describe the solution you'd like**
In case of test failures, I would like to see this in advance, e.g. in a yellow box "UNSTABLE". Then users would directly see if the issue is code related (yellow UNSTABLE) or infrastructure/build logic related (red, FAILED); [or timeout (black, TIMEOUT)]

**Comment by ib-steffen** [comment]
What should be the state if you had a failing test and your container returned an exit code != 0? Should the exit code take precedence?

**Comment by epDHowwD** [comment]
We can take over the behavior of jenkins, which is SUCCESS < UNSTABLE < FAILED < ABORTED.
So test failures are only considered if the build status is not already FAILED (container return code) or aborted. As InfraBox also knows the status TIMEOUT, I would place this between FAILED and ABORTED. Each event changing the build status can only increase it, never decrease it.
