### ISSUE TITLE
Unable to login to infrabox.ninja with GitHub credentials

### ISSUE THREAD

**Issue by ajmusto** [SAP/InfraBox#140]
**Describe the bug**
We are unable to login into InfraBox ninja using Github credentials
It says message | "Not allowed to signup"-- |  after succesful login into GitHub.

Also created an OAuth application in GitHub and provided the homepage url and callback url but still the issue persists.

**Comment by ib-steffen** [comment]
infrabox.ninja is not a public service, only InfraBox developers may use it for building and testing InfraBox.
If you want to use InfraBox you have to set it up in your kubernetes clusters. You may use `infrabox install` to get started quickly. See the installation guide https://github.com/SAP/InfraBox/blob/master/docs/install/install.md
