### ISSUE TITLE
INFRABOX_BUILD_NUMBER not substituting in CLI.

### ISSUE THREAD

**Issue by MitchGudmundson** [SAP/InfraBox#20]
**Describe the bug**
I am trying to publish a docker image from one job, and then specialize that image in downstream docker jobs. Thus I need an ARG in my Dockerfile which is INFRABOX_BUILD_NUMBER which I can reference as a tag in my FROM clause. Additionally, my deployments locally are not tagged with build_$INFRABOX_BUILD_NUMBER, but instead just "local". This pattern difference between CLI and remote will cause issues.

**To Reproduce**
infrabox.json
...
  "build_arguments": {
    "INFRABOX_BUILD_NUMBER": "$INFRABOX_BUILD_NUMBER"
  }

Dockerfile
ARG INFRABOX_BUILD_NUMBER
FROM registry/image:$INFRABOX_BUILD_NUMBER
...

**Expected behavior**
I would expect even locally that *something* be substituted for INFRABOX_BUILD_NUMBER so that this works properly both with CLI and remotely.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOSX High Sierra

**Additional context**

**Comment by ib-steffen** [comment]
Fix in CLI 0.6.8
