### ISSUE TITLE
Clone the repository only on the first job

### ISSUE THREAD

**Issue by PicoleDeLimao** [SAP/InfraBox#202]
Sometimes I get the error: File "/job/job.py", line 194, in clone_repo c.execute(['git', 'fetch', 'origin', commit], cwd=mount_repo_dir, show=True) File "/job/infrabox_job/process.py", line 26, in execute raise Exception('Command failed') Exception: Command failed

Due to: error: Server does not allow request for unadvertised object a7ebe8c970dbd7d8dcc31c12203a69e2839315b5

It may be because the repo is out of sync.... Does Infrabox clone the repo on every job? Cloning on the first job and somehow copying the repo to consecutive tasks could solve this issue

**Comment by ib-steffen** [comment]
duplicate #285
