### ISSUE TITLE
print current time in website footer

### ISSUE THREAD

**Issue by epDHowwD** [SAP/InfraBox#209]
**Is your feature request related to a problem? Please describe.**
InfraBox states 'started' at some time and as duration 'still running'. As the timestamp does not include any timezone or wintertime, it is unclear what infrabox thinks which time it is. 

**Describe the solution you'd like**
Print the current timestamp in website footer, so user can calculate delta on his/her own.

**Describe alternatives you've considered**
Do not print 'still running' but current duration.

**Comment by ib-steffen** [comment]
UI now shows dates in local timezone. Does this solve the issue alread? if not please reopen.
