### ISSUE TITLE
Console outputs is empty

### ISSUE THREAD

**Issue by hdifilwy** [SAP/InfraBox#239]
**Describe the bug**
In the latest infrabox jobs, we still experienced the empty console output sometimes.
https://infrabox.datahub.only.sap/dashboard/#/project/Hanalite-releasepack_Continues_validation/build/217/1/job/bdh-infra-tools%2Fvora_license_manager_test_gke

**To Reproduce**
Sporadic issue.

**Expected behavior**
The console outputs displayed.

**Comment by iberryful** [comment]
Fluentbit generates the following logs:
```
[2018/12/20 10:06:41] [error] [in_tail] could not register file into fs_events
[2018/12/20 10:06:43] [error] [plugins/in_tail/tail_fs.c:218 errno=28] No space left on device
```
I set `fs.inotify.max_user_watches=524288`, let's see what will happen

**Comment by ib-steffen** [comment]
closing this for now, please re-open if issue still exists.
