### ISSUE TITLE
Refreshing or following links to private projects go to dashboard

### ISSUE THREAD

**Issue by jerr0328** [SAP/InfraBox#257]
**Describe the bug**
If you are working with a private project in Infrabox and refresh the page, or try to follow a link to a private project, it will end up at the dashboard and sometimes show a toast saying "Unauthorized", even though the project is visible in the dashboard and the user is still logged in.

**To Reproduce**

0. Set up Github connection, users log in via Github
1. Create a private project, linked to a private Github repo.
2. Open the project in Infrabox (e.g. view the builds or a build step, whatever it might be)
3. Refresh the page
4. See error (redirected to dashboard)

Alternatively, you can try to follow a link, e.g. from the Slack notification, which will bring you to the dashboard. If you go to the build described by the link, the address bar shows the same, correct URL.

**Expected behavior**
I would expect that as long as I am logged in to the system, I can refresh the page and stay on the same page, or follow a deep link in the application and be put to the right place, even for private projects.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.2 (18C54)
 - Browser Chrome
 - Version 71.0.3578.98 (Official Build) (64-bit)

**Additional context**
We also have the issue of the websocket being reset every minute or so, which means we need to refresh more often until that issue is resolved on our end.

**Comment by jerr0328** [comment]
Still seeing this, although there's no toast about being unauthorized. I see in the console:
`GET <hostname>/api/v1/projects/name/<project> 401` from something in vue.js.

In the API logs:
```
28-01-2019:15:17:07,947 DEBUG [ibopa.py:21] Sending OPA Request: {"input": {"path": ["api", "v1", "settings"], "token": {"type": "user", "user": {"id": "58b4b171-1515-4076-b68e-6872f8a80b71"}}, "method": "GET"}}
28-01-2019:15:17:07,952 DEBUG [ibopa.py:24] OPA Response: {"result":true}
28-01-2019:15:17:07,983 DEBUG [ibopa.py:21] Sending OPA Request: {"input": {"path": ["api", "v1", "projects", "name", "<project name>"], "token": {"type": "user", "user": {"id": "58b4b171-1515-4076-b68e-6872f8a80b71"}}, "method": "GET"}}
28-01-2019:15:17:07,987 DEBUG [ibopa.py:24] OPA Response: {}
28-01-2019:15:17:07,987 INFO [ibflask.py:145] Rejected unauthorized request
28-01-2019:15:17:08,114 DEBUG [ibopa.py:21] Sending OPA Request: {"input": {"path": ["api", "v1", "user"], "token": {"type": "user", "user": {"id": "58b4b171-1515-4076-b68e-6872f8a80b71"}}, "method": "GET"}}
28-01-2019:15:17:08,118 DEBUG [ibopa.py:24] OPA Response: {"result":true}
28-01-2019:15:17:08,151 DEBUG [ibopa.py:21] Sending OPA Request: {"input": {"path": ["api", "v1", "projects"], "token": {"type": "user", "user": {"id": "58b4b171-1515-4076-b68e-6872f8a80b71"}}, "method": "GET"}}
28-01-2019:15:17:08,154 DEBUG [ibopa.py:24] OPA Response: {"result":true}
28-01-2019:15:17:08,199 DEBUG [ibopa.py:21] Sending OPA Request: {"input": {"path": ["api", "v1", "projects", "55e8ab82-eed0-480d-a321-0d149fd4f257", "jobs"], "token": {"type": "user", "user": {"id": "58b4b171-1515-4076-b68e-6872f8a80b71"}}, "method": "GET"}}
28-01-2019:15:17:08,201 DEBUG [ibopa.py:21] Sending OPA Request: {"input": {"path": ["api", "v1", "projects", "2d5f8e61-0aa3-48c3-a805-e2b8a70e44f7", "jobs"], "token": {"type": "user", "user": {"id": "58b4b171-1515-4076-b68e-6872f8a80b71"}}, "method": "GET"}}
28-01-2019:15:17:08,202 DEBUG [ibopa.py:21] Sending OPA Request: {"input": {"path": ["api", "v1", "projects", "cceb798f-f7b3-4a51-a8b1-94bb12f0aacd", "jobs"], "token": {"type": "user", "user": {"id": "58b4b171-1515-4076-b68e-6872f8a80b71"}}, "method": "GET"}}
28-01-2019:15:17:08,204 DEBUG [ibopa.py:21] Sending OPA Request: {"input": {"path": ["api", "v1", "projects", "a6090896-d56e-47d7-9e19-e0eb9b580c96", "jobs"], "token": {"type": "user", "user": {"id": "58b4b171-1515-4076-b68e-6872f8a80b71"}}, "method": "GET"}}
28-01-2019:15:17:08,209 DEBUG [ibopa.py:24] OPA Response: {"result":true}
28-01-2019:15:17:08,210 DEBUG [ibopa.py:24] OPA Response: {"result":true}
28-01-2019:15:17:08,211 DEBUG [ibopa.py:24] OPA Response: {"result":true}
28-01-2019:15:17:08,212 DEBUG [ibopa.py:24] OPA Response: {"result":true}
```

**Comment by jerr0328** [comment]
Just wanted to mention again that we are still seeing this issue.

**Comment by ib-steffen** [comment]
Sorry seems we missed your first message, we will check it again. thanks for letting us know.

**Comment by jerr0328** [comment]
I can confirm that the latest fix resolves the issue, thanks! 😃
