### ISSUE TITLE
Auto cancelling for new commits has resource leak potential

### ISSUE THREAD

**Issue by bymafmaf** [SAP/InfraBox#262]
When a new commit is pushed, the build is terminated. However, shutdown of the jobs are not graceful and since the whole build is cancelled, cleanup jobs cannot run even if they have `on: *` condition. This causes resource leaks for the jobs that provision/deprovision external resources.

Possible fix could be that even the whole build is cancelled, the jobs with `on: *` conditions could be run.

**Comment by ib-steffen** [comment]
This should be addressed by b8fd3fd868214ddb6d812405be1dcbac7d399326, a new commit does now only abort running jobs. This means if a parent is running and is aborted all children with `on: *` won't be aborted, but instead be executed. You can still have a situation where the actual cleanup job is running and is then aborted. This was possible all the time. So if you want to make sure that a certain job is always executed until successful completion then we would need to add a new feature. This is currently not possible (and was also not earlier).
