### ISSUE TITLE
"deployments" could push image even when the job failed.

### ISSUE THREAD

**Issue by hdifilwy** [SAP/InfraBox#281]
**Is your feature request related to a problem? Please describe.**
Regarding this:
https://github.com/SAP/InfraBox/blob/4a9825b9d067f49f338910c392d696af78ec6679/docs/job/deployments.md
We are trying to push all the images that run validation jobs.
However, it seems the "docker push" only work with the jobs that could run success.
The job in Red status won't execute the "docker push" step.

**Describe the solution you'd like**
Push docker images also when the job failed.

**Comment by ib-steffen** [comment]
has been fixed implemented in master
