### ISSUE TITLE
Infrabox INFRABOX_BUILD_RESTART_COUNTER default value is 1

### ISSUE THREAD

**Issue by PicoleDeLimao** [SAP/InfraBox#292]
The default value for INFRABOX_BUILD_RESTART_COUNTER is 1.
If you restart once, it will still be 1.
Only if you restart the job again it will become 2.
In my opinion, the default value should be 0.

**Comment by ib-steffen** [comment]
The first build has `INFRABOX_BUILD_RESTART_COUNTER=1`, it matches the build number in the UI i.e. `123.1`. If you restart a build you will get `INFRABOX_BUILD_RESTART_COUNTER=2` and the UI shows `123.2`. I cannot reproduce the case where you restart a build and it's still `INFRABOX_BUILD_RESTART_COUNTER=1`. So to me it looks like everything works as expected. Please reopen in case there's a way to reproduce some different behavior.
