### ISSUE TITLE
wrong link to trigger build when project has / in name

### ISSUE THREAD

**Issue by epDHowwD** [SAP/InfraBox#317]
Project link on UI:
`https://infrabox.datahub.only.sap/dashboard/#/project/velocity-infra/trigger-milestone-validation/trigger`
(escaping is of project name is wrong)

Should be
`https://infrabox.datahub.only.sap/dashboard/#/project/velocity-infra%2Ftrigger-milestone-validation/trigger`

**Comment by iberryful** [comment]
OK, I will  work on it.
