### ISSUE TITLE
retriggering jobs from retriggered generators breaks naming scheme

### ISSUE THREAD

**Issue by epDHowwD** [SAP/InfraBox#354]
**Describe the bug**
We use a generator to generate a larger workflow. After re-triggering the generator, we get falsely job names when re-triggering jobs generated by the _second_ generator.

**To Reproduce**
Create a generator G generating one or jobs including A, run it, retrigger G, retrigger A.

**Expected behavior**
We should have the jobs
* G
* G/A
* G.1
* G.1/A
* G.1/A.1

**Screenshots**
When we get is 
* G
* G/A
* G.1
* G.1/A
* ~G.1/A.1~ **G.2**
![Screenshot from 2019-09-02 08-23-56](https://user-images.githubusercontent.com/37585964/64094148-17693680-cd5b-11e9-8721-2ff0b598377f.png)

**Additional Context**
SAP-internal only: https://infrabox.datahub.only.sap/dashboard/#/project/hanalite-releasepack/build/10358/1

**Comment by iberryful** [comment]
fixed
