### ISSUE TITLE
The complete job output should be shown in the console (infrabox ui)

### ISSUE THREAD

**Issue by VasilyevaElena** [SAP/InfraBox#4]
If the output of a job is large, it is shown only partially with the following message:
"Output too large, only showing last 200 lines:"
It would be better, if the complete output can be shown.

**Comment by ib-steffen** [comment]
It's possible to access the full log trough the menu in the upper right corner. Is this sufficient?

**Comment by VasilyevaElena** [comment]
Yes, it is possible and is working. The issue can be closed.
