### ISSUE TITLE
Restart single job and keep jobs that depends on it not running.

### ISSUE THREAD

**Issue by hdifilwy** [SAP/InfraBox#403]
**Is your feature request related to a problem? Please describe.**
We have CI validation jobs running in infrabox. 
There are 50+ jobs in a infrabox build, execution with an order .
Some times, the job failed, we just need to restart a single one job but keep the rest jobs not running again.

**Describe the solution you'd like**
Run only one job but keep the jobs followed stay the original status.
Further more, we also have a "report" job at the end, so is that possible to run it and get the job status which restarted via the jobs.json ?
Example:
The first run:
job-A -> job-B -> job-C -> job-report

The job B failed, and I just want to restart this one. and also the job-report.
The second run:
job-a -> job-B.1 -> job-C ->job-report.1 (will the " job-report.1" be able to get the job status of "job-B.1") ?

**Comment by BigNuoLi** [comment]
please try this api call:

https://infrabox.datahub.only.sap/api/v1/projects/<project_id>/jobs/<job_id>/rerun

The "job_id" is the (failed) job which you want to rerun.
