### ISSUE TITLE
Support build targets for job type `docker`

### ISSUE THREAD

**Issue by elsbrock** [SAP/InfraBox#434]
**Is your feature request related to a problem? Please describe.**
I have a large Dockerfile with lots of stages, and I would like to build only a specific one.

**Describe the solution you'd like**
I would like to be able to tell IB which one to target (ie. equivalent of `docker build --target=…`).

**Describe alternatives you've considered**
Templating, but that does not work well with our internal build infrastructure

**Additional context**
n/a

**Comment by iberryful** [comment]
supported in https://github.com/SAP/InfraBox/pull/454
