### ISSUE TITLE
Documentation update: `generate_if` cases

### ISSUE THREAD

**Issue by agu3rra** [SAP/InfraBox#477]
Dear SAP InfraBox community,

I looked thru the docs but couldn't find examples or guides on how to use the `generate_if` statements in order to control how/when a job gets generated. Is there a place where I can find these and I may have missed it? I was looking for it in order to determine how to setup jobs to run only on specific events like on merge to certain branch patterns. I did find some examples coming from other repositories, but I believe it'd be great to have it on the docs section of this project.

Let me know if I can be of any help and I'll submit a PR.

An example I found was:
```yml
"generate_if": [
    {   "after_release": true },
    {   "matches_pattern": [
            "*.go",
            "infrabox/go-mod/*"
        ]
    },
    {   "cronjobs": [ "daily*" ] }
]
```
but what are other key words and settings I can use this section?

Thanks!

**Comment by iberryful** [comment]
The `generate_if` is a keyword in generator framework. It's not from infrabox.
