### ISSUE TITLE
Feature: enable selection of specific `--target` for `docker` job types; Kludgy workaround currently available.

### ISSUE THREAD

**Issue by agu3rra** [SAP/InfraBox#478]
## Feature
* enable the selection of a specific stage via the `--target` parameter on `docker build`. Ideally, this would also include the possibility to skip other stages, which in Docker is achieved by putting `DOCKER_BUILDKIT=1` in front of the `docker build` command.

## Workaround today (kludgy way)
I was able to use 
```yml
"build_arguments": {
     "DUMMY_ARG=FOOBAR --target": "builder"
},
```
This will generate the following execution `--build-arg DUMMY_ARG=FOOBAR --target=builder` and it works, but in a hacky way.

## Additional context
I want to enable an open-source vendor scanner that relies on the build stage in order to succeed. So my plan is to have a job that runs the build defined in a repository and use that generated image as the docker-image in which the scanner will run.

**Comment by iberryful** [comment]
supported in https://github.com/SAP/InfraBox/pull/454
