### ISSUE TITLE
pass the parameters to trigger the job

### ISSUE THREAD

**Issue by deldong** [SAP/InfraBox#482]
**Is your feature request related to a problem? Please describe.**
Our projects using infrabox.json to generated all our test automation cases. sometimes, we want to trigger one or more failed test cases to run or debug with the code that has been fixed the failed cases.

**Describe the solution you'd like**
It would be really nice if Infrabox can pass the parameters when triggering the job in Infrabox UI. just like the plugin of Jenkins named 'Build With Parameters Plugin'.
For example,  we have five test cases A, B, C, D, E. let's suppose A and B are failed in this round of tests, we can update the code to fix the failed cases and pass the failed cases name as parameters in Infrabox UI to debug the failed cases.
For example, let's suppose we have three environments, one is debugging for Dev, one is testing for QA, one is prod for release, we can pass the env as parameters to run test cases on env which you want to test.

**Describe alternatives you've considered**
currently, we use a stupid way to delete passed test cases from infrabox.json and keep the failed test cases to debug with updated code.

**Comment by iberryful** [comment]
It's currently supported to pass envs when trigger a build in the UI.
