### ISSUE TITLE
Error response from daemon: Get http://ha-eu-de-1.infrabox.datahub.only.sap/v2/: dial tcp 10.47.221.102:80: connect: connection refused

### ISSUE THREAD

**Issue by deldong** [SAP/InfraBox#484]
Describe the bug
There is a certain chance that the build fails with the error "Error response from daemon: Get http://ha-eu-de-1.infrabox.datahub.only.sap/v2/: dial tcp 10.47.221.102:80: connect: connection refused". or the error "
Error response from daemon: Get http://ha-eu-de-2.infrabox.datahub.only.sap/v2/: dial tcp 10.236.96.107:80: connect: connection refused".

To Reproduce
Restart the following job: https://infrabox.datahub.only.sap/dashboard/#/project/automation_test/build/1296/1

Expected behavior
Build the code successfully.

Screenshots
![image](https://user-images.githubusercontent.com/13015226/121306694-bc9e3f00-c931-11eb-8535-dca8c86bfa3e.png)

Additional context
1. After restarting the failed job several times, sometimes the job builds successfully, sometimes the job builds to fail.
2. The issue first appeared on June 8.

**Comment by iberryful** [comment]
fixed in production system
