### ISSUE TITLE
Logs cannot be downloaded: "The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again."

### ISSUE THREAD

**Issue by VasilyevaElena** [SAP/InfraBox#5]
The problem appears, if a multi-cloud option is used.
The job is done in a similar way as it is described in the examples. 
An image is built and deployed to a registry on the first step. On the second step, it is executed.
The problem appears for the second part: execution of the image on a gke cloud.
Its logs files are listed on the archive page, however, they cannot be downloaded because of the error:
"The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again."

**Comment by ib-steffen** [comment]
should have been fixed already
