### ISSUE TITLE
www.infrabox.net is down

### ISSUE THREAD

**Issue by earik87** [SAP/InfraBox#534]
The webpage for infrabox does not work and it looks like it is down.

**To Reproduce**
1. Go to ['Infrabox Github Page'](https://github.com/SAP/InfraBox)
2. Click on 'www.infrabox.net' under the about section.
3. See error.

**Expected behavior**
The website should work.

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [chrome]

**Comment by mbtools** [comment]
And the "Build Status" badge in the readme doesn't work either. Is this project dead?

![image](https://github.com/user-attachments/assets/fd759b4a-300f-48f9-83d0-1248f861cfa6)
