### ISSUE TITLE
Job abort without any details 

### ISSUE THREAD

**Issue by hdifilwy** [SAP/InfraBox#61]
For example:

https://infrabox.datahub.only.sap/dashboard/#/project/Hananlite-Releasepack-nightly-dev/build/16/1/job/bdh-infra-tools%2Fbuild_ui-test

Seems the job abort in the docker build stages. 
But no more details for troubleshooting.

**Comment by ib-steffen** [comment]
we applied a fix in the cluster, please reopen if you see the issue again
