### ISSUE TITLE
File name should be preserved in download from Archive

### ISSUE THREAD

**Issue by Steffen911** [SAP/InfraBox#63]
**Describe the bug**
If I download a file, e.g. `logs.zip` from the Archive tab of a job it gets saved as `download`. In this case I need to manually change the file type to `.zip` to be able to extract the contents.

**To Reproduce**
1. Go to `Archive`
2. Click on the file you want to download
3. You should find a file `download` in your Downloads folder

**Expected behavior**
The file should be saved locally under the same name as in the Archive tab, e.g. `logs.zip`

**Comment by ib-steffen** [comment]
This should have been fixed in the meantime.
