### ISSUE TITLE
Support Jacoco Code Coverage Results

### ISSUE THREAD

**Issue by MitchGudmundson** [SAP/InfraBox#85]
**Is your feature request related to a problem? Please describe.**
Our projects are using Jacoco for code coverage reporting. Currently we need to use a custom script which converts the structure of the Jacoco reports to that of Cobertura.

**Describe the solution you'd like**
It would be really nice if Infrabox natively supported both Jacoco and Cobertura as Jacoco is another popular code coverage tool that's used.

**Describe alternatives you've considered**
As described above, currently have to script a process to convert from Jacoco format to Cobertura.

**Additional context**

**Comment by ib-steffen** [comment]
Hi,

do you already have a scr
