### ISSUE TITLE
Uploaded txt files are not readable

### ISSUE THREAD

**Issue by VasilyevaElena** [SAP/InfraBox#98]
**Describe the bug**
Text log files uploaded into the are not readable.

**To Reproduce**
1. Run your job, which has the function on exit:
`
function cleanup {
    if [ -d "logs" ]; then
        mv  -v logs /infrabox/upload/archive/installation_logs
    else
        echo "Installation logs do not exist."
        ls -la
    fi
}
trap cleanup EXIT
`

2. After the job failed, try to download and open the logs
3. See unreadable content

**Expected behavior**
I expect that the files can be read

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome   
 - Version 67.0.3396.99

**Additional context**
The same problem happens to all files copied into output.

**Comment by epDHowwD** [comment]
fixed with https://github.com/SAP/InfraBox/pull/100
